### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fartabomination** [XayOn/ackack#1]
Will this work using the built in camera on the robot?

**Comment by XayOn** [comment]
Well, this was designed for a robot that doesn't have a camera, so I don't know wich one you're referring to :)

**Comment by fartabomination** [comment]
> Well, this was designed for a robot that doesn't have a camera, so I don't know wich one you're referring to :)

I’m referring to the J series.

**Comment by XayOn** [comment]
I can't find any neatsvor j-series, do you have a link? Anyway, this software is designed to work togheter with a yi-camera, won't work (without a lot of work) with any other

**Comment by fartabomination** [comment]
> I can't find any neatsvor j-series, do you have a link? Anyway, this software is designed to work togheter with a yi-camera, won't work (without a lot of work) with any other

Sure https://www.irobot.com.au/roomba/j-series

**Comment by XayOn** [comment]
Oh, this is for WEBACK robots, it doesn't support roombas at all.
